spring:
    application:
        name: streef
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/simi
        username: simi
        password: simi
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
springdoc:
    swagger-ui:
        path: /swagger-ui.html

# Custom
geo:
    admin:
        api:
            height-url: https://api3.geo.admin.ch/rest/services/height

#    datasource:
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password: 
#        driverClassName: org.h2.Driver
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect